package com.example.pc5.ventasyesi.Mapeo;
// Generated 08-nov-2015 14:48:03 by Hibernate Tools 4.3.1



/**
 * DetalleListId generated by hbm2java
 */
public class DetalleListId  implements java.io.Serializable {


     private String codp;
     private String codl;

    public DetalleListId() {
    }

    public DetalleListId(String codp, String codl) {
       this.codp = codp;
       this.codl = codl;
    }
   
    public String getCodp() {
        return this.codp;
    }
    
    public void setCodp(String codp) {
        this.codp = codp;
    }
    public String getCodl() {
        return this.codl;
    }
    
    public void setCodl(String codl) {
        this.codl = codl;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleListId) ) return false;
		 DetalleListId castOther = ( DetalleListId ) other; 
         
		 return ( (this.getCodp()==castOther.getCodp()) || ( this.getCodp()!=null && castOther.getCodp()!=null && this.getCodp().equals(castOther.getCodp()) ) )
 && ( (this.getCodl()==castOther.getCodl()) || ( this.getCodl()!=null && castOther.getCodl()!=null && this.getCodl().equals(castOther.getCodl()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodp() == null ? 0 : this.getCodp().hashCode() );
         result = 37 * result + ( getCodl() == null ? 0 : this.getCodl().hashCode() );
         return result;
   }   


}


