package com.example.pc5.ventasyesi.Mapeo;
// Generated 08-nov-2015 14:48:03 by Hibernate Tools 4.3.1



/**
 * DetalleList generated by hbm2java
 */
public class DetalleList  implements java.io.Serializable {


     private DetalleListId id;
     private Listas listas;
     private Producto producto;
     private int Id;
     private int Codp;
     private int Codl;
     private int Cantidad;
     private String Estado; //cambie string por char

    public DetalleList() {
    }

    public DetalleList(DetalleListId id, Listas listas, Producto producto,int Id,int Codp,int Codl, int Cantidad, String Estado) {
       this.id = id;
       this.listas = listas;
       this.producto = producto;
       this.Id= Id;
       this.Codp=Codp;
       this.Codl=Codl;
       this.Cantidad = Cantidad;
       this.Estado = Estado;
    }
   
    public DetalleListId getId() {
        return this.id;
    }
    
    public void setId(DetalleListId id) {
        this.id = id;
    }
    public Listas getListas() {
        return this.listas;
    }
    
    public void setListas(Listas listas) {
        this.listas = listas;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.Cantidad;
    }
    
    public void setCantidad(int Cantidad) {
        this.Cantidad = Cantidad;
    }
    public String getEstado() {
        return this.Estado;
    }
    
    public void setEstado(String Estado) {
        this.Estado = Estado;
    }

    public int getIds() {
        return this.Id;
    }

    public void setIds(int Id) {
        this.Id = Id;
    }

    public int getCodp() {
        return this.Codp;
    }

    public void setCodp(int Codp) {
        this.Codp = Codp;
    }

    public int getCodl() {
        return this.Codl;
    }

    public void setCodl(int Codl) {
        this.Codl = Codl;
    }


}


