package com.example.pc5.ventasyesi.Mapeo;
// Generated 08-nov-2015 14:48:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Listas generated by hbm2java
 */
public class Listas  implements java.io.Serializable {
///ya

     private int Codl;
     private String Nombre;
     private String Tipo;
     private Set listUsus = new HashSet(0);
     private Set detalleLists = new HashSet(0);

    public Listas() {
    }

	
    public Listas(int Codl, String Nombre, String Tipo) {
        this.Codl = Codl;
        this.Nombre = Nombre;
        this.Tipo = Tipo;
    }
    public Listas(int Codl, String Nombre, String Tipo, Set listUsus, Set detalleLists) {
       this.Codl = Codl;
       this.Nombre = Nombre;
       this.Tipo = Tipo;
       this.listUsus = listUsus;
       this.detalleLists = detalleLists;
    }
   
    public int getCodl() {
        return this.Codl;
    }
    
    public void setCodl(int Codl) {
        this.Codl = Codl;
    }
    public String getNombre() {
        return this.Nombre;
    }
    
    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }
    public String getTipo() {
        return this.Tipo;
    }
    
    public void setTipo(String Tipo) {
        this.Tipo = Tipo;
    }
    public Set getListUsus() {
        return this.listUsus;
    }
    
    public void setListUsus(Set listUsus) {
        this.listUsus = listUsus;
    }
    public Set getDetalleLists() {
        return this.detalleLists;
    }
    
    public void setDetalleLists(Set detalleLists) {
        this.detalleLists = detalleLists;
    }




}


