package com.example.pc5.ventasyesi.Mapeo;
// Generated 08-nov-2015 14:48:03 by Hibernate Tools 4.3.1



/**
 * ListUsuId generated by hbm2java
 */
public class ListUsuId  implements java.io.Serializable {


     private String codl;
     private String codus;

    public ListUsuId() {
    }

    public ListUsuId(String codl, String codus) {
       this.codl = codl;
       this.codus = codus;
    }
   
    public String getCodl() {
        return this.codl;
    }
    
    public void setCodl(String codl) {
        this.codl = codl;
    }
    public String getCodus() {
        return this.codus;
    }
    
    public void setCodus(String codus) {
        this.codus = codus;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ListUsuId) ) return false;
		 ListUsuId castOther = ( ListUsuId ) other; 
         
		 return ( (this.getCodl()==castOther.getCodl()) || ( this.getCodl()!=null && castOther.getCodl()!=null && this.getCodl().equals(castOther.getCodl()) ) )
 && ( (this.getCodus()==castOther.getCodus()) || ( this.getCodus()!=null && castOther.getCodus()!=null && this.getCodus().equals(castOther.getCodus()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodl() == null ? 0 : this.getCodl().hashCode() );
         result = 37 * result + ( getCodus() == null ? 0 : this.getCodus().hashCode() );
         return result;
   }   


}


