package com.example.pc5.ventasyesi.Mapeo;
// Generated 08-nov-2015 14:48:03 by Hibernate Tools 4.3.1



/**
 * Super generated by hbm2java
 */
public class Super  implements java.io.Serializable {


     private int Cods;
     private String Nombre;
     private double Longitud;
     private double Latitud;
     private String Cuenta;
     private String Clave;

    public Super() {
    }

    public Super(int Cods, String Nombre, double Longitud, double Latitud,String Cuenta,String Clave) {
       this.Cods = Cods;
       this.Nombre = Nombre;
       this.Longitud = Longitud;
       this.Latitud = Latitud;
       this.Cuenta=Cuenta;
       this.Clave=Clave;
    }
   
    public int getCods() {
        return this.Cods;
    }
    
    public void setCods(int Cods) {
        this.Cods = Cods;
    }
    public String getNombre() {
        return this.Nombre;
    }
    
    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }
    public double getLongitud() {
        return this.Longitud;
    }
    
    public void setLongitud(double Longitud) {
        this.Longitud = Longitud;
    }
    public double getLatitud() {
        return this.Latitud;
    }
    
    public void setLatitud(double Latitud) {
        this.Latitud = Latitud;
    }

    public String getCuenta() {
        return this.Cuenta;
    }

    public void setCuenta(String Cuenta) {
        this.Cuenta = Cuenta;
    }

    public String getClave() {
        return this.Clave;
    }

    public void setClave(String Clave) {
        this.Clave = Clave;
    }


}


