package com.example.pc5.ventasyesi.Mapeo;
// Generated 08-nov-2015 14:48:03 by Hibernate Tools 4.3.1



/**
 * Unidad generated by hbm2java
 */
public class Unidad  implements java.io.Serializable {


     private String Codu;
     private String Nombre;

    public Unidad() {
    }

    public Unidad(String Codu, String Nombre) {
       this.Codu = Codu;
       this.Nombre = Nombre;
    }
   
    public String getCodu() {
        return this.Codu;
    }
    
    public void setCodu(String Codu) {
        this.Codu = Codu;
    }
    public String getNombre() {
        return this.Nombre;
    }
    
    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }




}


